### PR TITLE
fix(hooks): different PATH's name on windows and linux

### LINKED ISSUE #370: Running under PowerShell fails to invoke `git` in hooks
### Description of the bug

Moving commit generates a warning and leaves the old commit in place.
I'm on Windows 11, in a PowerShell terminal. 

```
⋮
◇ f148352 13d (remote origin/main) Fix up renamed csproj
┃
◯ 777ac1f 8s file1
┃
● 9c3f752 1s file2
D:\Projects\Git\ExpressionTree > git move -s HEAD -d f148352
Attempting rebase in-memory...
[1/1] Committed as: 62e3191 file2
/d/Projects/Git/ExpressionTree/.git/hooks/reference-transaction: line 6: git: command not found
branchless: Failed to process reference transaction!
branchless: Some events (e.g. branch updates) may have been lost.
branchless: This is a bug. Please report it.
/d/Projects/Git/ExpressionTree/.git/hooks/post-rewrite: line 4: git: command not found
branchless: running command: git checkout 62e3191f2ff4bae240bf82e4f9e2532b75b9b43a
Previous HEAD position was 9c3f752 file2
branchless: processing 1 update: ref HEAD
HEAD is now at 62e3191 file2
branchless: processing checkout
branchless: running command: git branchless smartlog
:
O f148352 13d (remote origin/main) Fix up renamed csproj
|\
| o 777ac1f 15s file1
| |
| o 9c3f752 8s file2
|
@ 62e3191 1s file2
In-memory rebase succeeded.
```

### Expected behavior

I expected the HEAD commit to be moved to be a child of origin/main. 

### Actual behavior

- Warning generated about not being able to find git.
- Commit cherry-picked to the correct location but original commits are still visible. 

### Version of `git-branchless`

git-branchless 0.3.12

### Version of `git`

git version 2.35.1.windows.2

### Version of `rustc`

rustc 1.57.0 (f1edd0429 2021-11-29)

#### Software version

git-branchless 0.3.12

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
git-branchless bug-report 
```

#### Environment variables

```bash
SHELL=<not set>
EDITOR=<not set>
```

#### Git version

```
> git version 
git version 2.35.1.windows.2
```

#### Events

<details>
<summary>Show 5 events</summary>

##### Event ID: 151, transaction ID: 288

1. `RefUpdateEvent { timestamp: 1650762474.984679, event_tx_id: EventTransactionId(288), ref_name: "HEAD", old_oid: 0000000000000000000000000000000000000000, new_oid: 62e3191f2ff4bae240bf82e4f9e2532b75b9b43a, message: None }`
1. `RefUpdateEvent { timestamp: 1650762475.0473373, event_tx_id: EventTransactionId(288), ref_name: "HEAD", old_oid: 9c3f7524633c5c38a57c47ec51d91b768557aa5a, new_oid: 62e3191f2ff4bae240bf82e4f9e2532b75b9b43a, message: None }`
```
:
O f148352 13d (remote origin/main) xxx xx xxxxxxx xxxxxx
|\
| o 777ac1f 5m xxxxx
| |
| o 9c3f752 5m xxxxx
|
@ 62e3191 5m xxxxx
```
##### Event ID: 149, transaction ID: 286

1. `RefUpdateEvent { timestamp: 1650762467.3501792, event_tx_id: EventTransactionId(286), ref_name: "HEAD", old_oid: 777ac1f503f886aa09ea66499a7a993642b726ed, new_oid: 9c3f7524633c5c38a57c47ec51d91b768557aa5a, message: None }`
1. `CommitEvent { timestamp: 1650762467.0, event_tx_id: EventTransactionId(286), commit_oid: NonZeroOid(9c3f7524633c5c38a57c47ec51d91b768557aa5a) }`
```
:
O f148352 13d (remote origin/main) xxx xx xxxxxxx xxxxxx
|\
| o 777ac1f 5m xxxxx
| |
| o 9c3f752 5m xxxxx
|
@ 62e3191 5m xxxxx
```
##### Event ID: 147, transaction ID: 284

1. `RefUpdateEvent { timestamp: 1650762460.6356707, event_tx_id: EventTransactionId(284), ref_name: "HEAD", old_oid: f148352480d981f078b609f5a49870baa2e6d107, new_oid: 777ac1f503f886aa09ea66499a7a993642b726ed, message: None }`
1. `CommitEvent { timestamp: 1650762460.0, event_tx_id: EventTransactionId(284), commit_oid: NonZeroOid(777ac1f503f886aa09ea66499a7a993642b726ed) }`
```
:
O f148352 13d (remote origin/main) xxx xx xxxxxxx xxxxxx
|\
| o 777ac1f 5m xxxxx
| |
| o 9c3f752 5m xxxxx
|
@ 62e3191 5m xxxxx
```
##### Event ID: 145, transaction ID: 280

1. `RefUpdateEvent { timestamp: 1650762410.2934084, event_tx_id: EventTransactionId(280), ref_name: "HEAD", old_oid: 0000000000000000000000000000000000000000, new_oid: f148352480d981f078b609f5a49870baa2e6d107, message: None }`
1. `RefUpdateEvent { timestamp: 1650762410.4033375, event_tx_id: EventTransactionId(280), ref_name: "HEAD", old_oid: a1d0e44057382e04c4c3b8c97e45476a531da573, new_oid: f148352480d981f078b609f5a49870baa2e6d107, message: None }`
```
:
O f148352 13d (remote origin/main) xxx xx xxxxxxx xxxxxx
|\
| o 777ac1f 5m xxxxx
| |
| o 9c3f752 5m xxxxx
|
@ 62e3191 5m xxxxx
```
##### Event ID: 137, transaction ID: 278

1. `ObsoleteEvent { timestamp: 1650762402.4933422, event_tx_id: EventTransactionId(278), commit_oid: NonZeroOid(8d637802135c65b18ae4ee74b6e843ca9f65fcbd) }`
1. `ObsoleteEvent { timestamp: 1650762402.4933422, event_tx_id: EventTransactionId(278), commit_oid: NonZeroOid(0917e2432c2088cad223936d1f083fcc4b01535a) }`
1. `ObsoleteEvent { timestamp: 1650762402.4933422, event_tx_id: EventTransactionId(278), commit_oid: NonZeroOid(a2a2267cc32a5c6b0e78def64aff016235ae9c27) }`
1. `ObsoleteEvent { timestamp: 1650762402.4933422, event_tx_id: EventTransactionId(278), commit_oid: NonZeroOid(1531d1efb28c142256b81d7ca17ff3e4c5147e78) }`
1. `ObsoleteEvent { timestamp: 1650762402.4933422, event_tx_id: EventTransactionId(278), commit_oid: NonZeroOid(385c75dda30476f5301e083367a8eeecc36cd4ef) }`
1. `ObsoleteEvent { timestamp: 1650762402.4933422, event_tx_id: EventTransactionId(278), commit_oid: NonZeroOid(2a4949f6cbaec426b020f8bb17dab807dcdac7d1) }`
1. `ObsoleteEvent { timestamp: 1650762402.4933422, event_tx_id: EventTransactionId(278), commit_oid: NonZeroOid(618594b6577643ea1cece6d4a4ac0a0f59ea0e36) }`
1. `ObsoleteEvent { timestamp: 1650762402.4933422, event_tx_id: EventTransactionId(278), commit_oid: NonZeroOid(a1d0e44057382e04c4c3b8c97e45476a531da573) }`
```
:
O f148352 13d (remote origin/main) xxx xx xxxxxxx xxxxxx
|\
| o 777ac1f 5m xxxxx
| |
| o 9c3f752 5m xxxxx
|
@ 62e3191 5m xxxxx
```

</details>

### LINKED ISSUE #1144: `git move -x` leads to commit disappearing (branchless: Failed to process reference transaction!)
### Description of the bug

Probably I did something stupid (I've only been using this tool for a few weeks), but here's what happened:
- I initialized git-branchless as I was using a new computer
- I had a branch with some commits I wanted to move to a different location
So I used `git move -x <commit hash>`. This led to the following output:

```
git move -x 2af5d7e
Attempting rebase in-memory...
[1/4] Committed as: 9f1cde7 made deprecated res/profile refer to new router function
[2/4] Committed as: 77a43fe fix: authpage no longer submits when pressing forgot password
[3/4] Committed as: 5140268 logging for update password
[4/4] Committed as: 2b10a6d add logging for getting birthday, profile and change email, onboard
/c/Users/Student/Documents/GitHub/backend/.git/hooks/reference-transaction: line 6: git: command not found
branchless: Failed to process reference transaction!
branchless: Some events (e.g. branch updates) may have been lost.
branchless: This is a bug. Please report it.
/c/Users/Student/Documents/GitHub/backend/.git/hooks/post-rewrite: line 4: git: command not found
branchless: creating working copy snapshot
branchless: running command: git checkout main
Your branch is up to date with 'origin/main'.
Switched to branch 'main'
branchless: processing checkout
``` 

For reference, this was my `git sl` before:
```
◇ 01bbc15 4d fix: revert changing category to primary_key, was not supposed to be committed
┣━┓
⋮ ◯ 6e90a80 4d feat: Dodeka logo and improve alignment
⋮ ┃
⋮ ◯ 9d482d6 3h remove gunicorn.sh as no longer used
⋮ ┃
⋮ ◯ cb38414 10m fix: default eduinstitution now set
⋮ ┃
⋮ ◯ 2af5d7e 10m add logging for getting birthday, profile and change email, onboard
⋮ ┃
⋮ ◯ 6028c90 10m made deprecated res/profile refer to new router function
⋮ ┃
⋮ ◯ abf0d0f 10m fix: authpage no longer submits when pressing forgot password
⋮ ┃
⋮ ◯ 7da0aa3 10m (improve-authpage) logging for update password
⋮
◆ d9b20d8 5m (chore/more-logging, ᐅ main) remove gunicorn.sh as no longer used
```

After:

```
◇ 01bbc15 4d fix: revert changing category to primary_key, was not supposed to be committed
┣━┓
⋮ ◯ 6e90a80 4d feat: Dodeka logo and improve alignment
⋮ ┃
⋮ ◯ 9d482d6 3h remove gunicorn.sh as no longer used
⋮ ┃
⋮ ◯ cb38414 11m fix: default eduinstitution now set
⋮ ┃
⋮ ◯ 9f1cde7 1s made deprecated res/profile refer to new router function
⋮ ┃
⋮ ◯ 77a43fe 1s fix: authpage no longer submits when pressing forgot password
⋮ ┃
⋮ ◯ 5140268 1s (improve-authpage) logging for update password
⋮
◆ d9b20d8 5m (chore/more-logging, ᐅ main) remove gunicorn.sh as no longer used
```

`git-branchless` was installed using `cargo install`, using v0.8. I just updated Git to 2.43. The commit I moved, `2af5d7e` was invisible. Running git undo changed nothing:

```
Will apply these actions:
1. Check out from d9b20d8 remove gunicorn.sh as no longer used
               to d9b20d8 remove gunicorn.sh as no longer used
2. Restore snapshot for d9b20d8 remove gunicorn.sh as no longer used
        backed up using dd7cee0 branchless: automated working copy snapshot
Confirm? [yN] y
branchless: creating working copy snapshot
branchless: running command: git checkout dd7cee0df4fa8194f1cfd8c366910d7913885aa7
Previous HEAD position was d9b20d8 remove gunicorn.sh as no longer used
branchless: processing 1 update: ref HEAD
HEAD is now at dd7cee0 branchless: automated working copy snapshot
branchless: processing checkout
branchless: restoring from snapshot
branchless: running command: git reset --hard HEAD
branchless: processing 1 update: ref HEAD
HEAD is now at dd7cee0 branchless: automated working copy snapshot
branchless: running command: git checkout 3e5d6fe3a882f2e53562104be6494f71d1cbd10b
Warning: you are leaving 5 commits behind, not connected to
any of your branches:
  dd7cee0 branchless: automated working copy snapshot                                                                                                                 
  4ebbb86 branchless: working copy snapshot data: 0 changes in stage 0
  7f8636f branchless: working copy snapshot data: 0 changes in stage 1
  64a91eb branchless: working copy snapshot data: 0 changes in stage 2
  8b98943 branchless: working copy snapshot data: 0 changes in stage 3
branchless: processing 1 update: ref HEAD
HEAD is now at 3e5d6fe branchless: working copy snapshot data: 0 unstaged changes
branchless: processing checkout
branchless: running command: git reset d9b20d80e7e4988260eaa166753778fb475df55f
branchless: processing 1 update: ref HEAD
⋮
◇ 01bbc15 4d fix: revert changing category to primary_key, was not supposed to be committed
┣━┓
⋮ ◯ 6e90a80 4d feat: Dodeka logo and improve alignment
⋮ ┃
⋮ ◯ 9d482d6 3h remove gunicorn.sh as no longer used
⋮ ┃
⋮ ◯ cb38414 12m fix: default eduinstitution now set
⋮ ┃
⋮ ◯ 9f1cde7 1m made deprecated res/profile refer to new router function
⋮ ┃
⋮ ◯ 77a43fe 1m fix: authpage no longer submits when pressing forgot password
⋮ ┃
⋮ ◯ 5140268 1m (improve-authpage) logging for update password
⋮
◆ d9b20d8 7m (chore/more-logging, main) remove gunicorn.sh as no longer used
```
Using `git unhide` I was able to restore the commit:

```
◇ 01bbc15 4d fix: revert changing category to primary_key, was not supposed to be committed
┣━┓
⋮ ◯ 6e90a80 4d feat: Dodeka logo and improve alignment
⋮ ┃
⋮ ◯ 9d482d6 4h remove gunicorn.sh as no longer used
⋮ ┃
⋮ ◯ cb38414 16m fix: default eduinstitution now set
⋮ ┣━┓
⋮ ┃ ◯ 2af5d7e 16m add logging for getting birthday, profile and change email, onboard
⋮ ┃
⋮ ◯ 9f1cde7 5m made deprecated res/profile refer to new router function
⋮ ┃
⋮ ◯ 77a43fe 5m fix: authpage no longer submits when pressing forgot password
⋮ ┃
⋮ ◯ 5140268 5m (improve-authpage) logging for update password
⋮
◆ d9b20d8 11m (chore/more-logging, main) remove gunicorn.sh as no longer used
```

I'm aware that doing something similar is used to remove commits from a branch, but I was under the impression that they should be visible somewhere at least? Also because of the error indicated, I believe something is going wrong. My apologies if I'm misunderstanding the commands.

Also, thanks a lot for this tool! I'm slowly migrating to a more branchless/stacking workflow, but as you can see sometimes I still rely on my old trusted branches.

### Expected behavior

Commit was moved on top of HEAD (main branch in this case) and removed from the list of commits on the other branch. Commit doesn't disappear, git-branchless doesn't give an error.

### Actual behavior

Commit was hidden. 

### Version of `rustc`

1.73.0

#### Software version

git-branchless 0.8.0

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
git-branchless bug-report
```

#### Environment variables

```bash
SHELL=<not set>
EDITOR=<not set>
```

#### Git version

```
> git version
git version 2.43.0.windows.1
```

#### Hooks

<details>
<summary>Show 7 hooks</summary>

##### Hook `post-applypatch`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook post-applypatch "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-checkout`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook post-checkout "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-commit`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook post-commit "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-merge`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook post-merge "$@"

## END BRANCHLESS CONFIG
```
##### Hook `post-rewrite`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook post-rewrite "$@"

## END BRANCHLESS CONFIG
```
##### Hook `pre-auto-gc`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook pre-auto-gc "$@"

## END BRANCHLESS CONFIG
```
##### Hook `reference-transaction`

```
#!/bin/sh
## START BRANCHLESS CONFIG

# Avoid canceling the reference transaction in the case that `branchless` fails
# for whatever reason.
git branchless hook reference-transaction "$@" || (
echo 'branchless: Failed to process reference transaction!'
echo 'branchless: Some events (e.g. branch updates) may have been lost.'
echo 'branchless: This is a bug. Please report it.'
)

## END BRANCHLESS CONFIG
```

</details>

#### Events

<details>
<summary>Show 5 events</summary>

##### Event ID: 37, transaction ID: 24 (message: unhide)

1. `UnobsoleteEvent { timestamp: 1701606761.9774282, event_tx_id: EventTransactionId(24), commit_oid: NonZeroOid(2af5d7e0a6426b3eaa6cda3701555b763f4568bf) }`
```
:
O da56717 258d xxxx xxxx xxxxx
|\
: o ec7bff6 254d (redacted-ref-0) xxxxxx xxxx
:
O 41f217a 75d (redacted-ref-1) xxxx xxx xxxx xx xxxxx
:
O b4de865 59d xxxxxx xxx xxxxx xxxxx
|\
: o 566ac90 59d (redacted-ref-2) xxxx xxxxxxxxx xxx xxxx
:
O c4a74e0 28d (redacted-ref-3) xxxx xxx xxxxxxxxx xxx xxxxxxx xxxx xxxx xxxxxxxxxx xxx xxxx xxx xxx xxxx
:
O 2ae7c32 28d (redacted-ref-4) xxxxx xxxxx xxxxxxx xxxxxxx xxxxxxx xx xx xxxx xxxx xxxxxxx xxxx
:
O 53fbd66 26d (redacted-ref-5) xxxxxx xxxxx xxxxxx xxx xxxx xxxxxxxxxx
:
O c88160a 26d xxxxx xxxx xxxxxxx xxx xxxx xxxxxxxxxxxxxxxxxx
|\
| o 6c1960f 26d xxxxx xxxxx xxxx xxxxx xxxx
| |
| o 7624998 25d xxxxx xxx xxxxxxxxxxx
| |
| o 8dfbbc6 25d xxxx xxxx xxxxx xxxxxxx xxx xxxxx
| |
| o 90fbfaa 25d xxx xxxxx xxxx
| |
| o 4c2f136 25d xxxx xxxx xxx xxx xxxxx xxxx
| |
| o 898bdc9 25d xxxx xxxxxx xx
| |
| o 02407ec 25d xxxxx xxxxxx xxxxxx
| |
| o fe949e3 25d xxxx xxxxx xx xxxxxx xx xxxxxxx xxxx
| |
| o 00139fc 25d xxxx xxxxxxxxx xxxx xx xxxxxx
| |
| o 7848514 25d xxxxxx xxxxxx
| |
| o 8be9311 25d xxxx xxxxx xxxx xxxxxx xxxxx
| |
| o 014b13a 25d (redacted-ref-6) xxxxxxxx
|
O d12c188 25d xxxxx xxxx xxxxx
|\
: o e108478 25d xxxxx xxxxxx xxxxxxxxxxxxxx
: |
: o f7af8f9 25d xxxx xxxx
: |
: o 2e2b044 25d xxxx xxxx xxxx xxxxxxx
: |
: o b6e474c 25d xxxxxx xxxx xxxxxx xxxxxx xxxx xxxx xx xxxx xxxx xxxxx xx xx
: |
: o 48dc8b5 25d xxxx xxxxxx xxxxxx xxxxxxxx xx xxxx
: |
: o a3f5b28 25d xxxx xxxxxxxx xxxxxx xx
: |
: o ca2fe47 25d xxxx xxx xxxxxx xxxxx xxxxx
: |
: o 6cbec51 25d xxxx xxxxxx xxxxx
: |
: o b1cad43 25d xxxx xxxxxx xxxxx xxxxx
: |
: o 56b56d9 25d xxxxx xxxx xxxx xx xxxxxx
: |
: o 0b850a8 25d xxxxx xxx xx xx xxx xxx xx
: |
: o f08112a 25d xxxx xxxx xxxxxx xxxx xxx xxxx xxxxxxxxx
: |
: o 61f71fb 24d (redacted-ref-7) xxxxxxxxxxxxxx xxxxxxxxxxxxxx xxxxxxx xxxxxxx xxx xxxxxxx xxxx
:
O 68491a7 23d (redacted-ref-8) xxxxxxxxx xxxx xxxxxxx
:
O 01bbc15 4d xxxx xxxxxx xxxxxxxx xxxxxxxx xx xxxxxxxxxxxx xxx xxx xxxxxxxx xx xx xxxxxxxxx
|\
: o 6e90a80 4d xxxxx xxxxxx xxxx xxx xxxxxxx xxxxxxxxx
: |
: o 9d482d6 4h xxxxxx xxxxxxxxxxx xx xx xxxxxx xxxx
: |
: o cb38414 26m xxxx xxxxxxx xxxxxxxxxxxxxx xxx xxx
: |\
: | o 2af5d7e 26m xxx xxxxxxx xxx xxxxxxx xxxxxxxxx xxxxxxx xxx xxxxxx xxxxxx xxxxxxx
: |
: o 9f1cde7 15m xxxx xxxxxxxxxx xxxxxxxxxxx xxxxx xx xxx xxxxxx xxxxxxxx
: |
: o 77a43fe 15m xxxx xxxxxxxx xx xxxxxx xxxxxxx xxxx xxxxxxxx xxxxxx xxxxxxxx
: |
: o 5140268 15m (redacted-ref-9) xxxxxxx xxx xxxxxx xxxxxxxx
:
@ d9b20d8 21m (main, redacted-ref-10) xxxxxx xxxxxxxxxxx xx xx xxxxxx xxxx
```
##### Event ID: 30, transaction ID: 22 (message: undo)

1. `WorkingCopySnapshot { timestamp: 1701606651.5180635, event_tx_id: EventTransactionId(22), head_oid: d9b20d80e7e4988260eaa166753778fb475df55f, commit_oid: NonZeroOid(dd7cee0df4fa8194f1cfd8c366910d7913885aa7), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1701606651.7743325, event_tx_id: EventTransactionId(22), ref_name: ReferenceName("HEAD"), old_oid: 0000000000000000000000000000000000000000, new_oid: dd7cee0df4fa8194f1cfd8c366910d7913885aa7, message: None }`
1. `RefUpdateEvent { timestamp: 1701606651.8856702, event_tx_id: EventTransactionId(22), ref_name: ReferenceName("HEAD"), old_oid: d9b20d80e7e4988260eaa166753778fb475df55f, new_oid: dd7cee0df4fa8194f1cfd8c366910d7913885aa7, message: None }`
1. `RefUpdateEvent { timestamp: 1701606652.3215134, event_tx_id: EventTransactionId(22), ref_name: ReferenceName("HEAD"), old_oid: dd7cee0df4fa8194f1cfd8c366910d7913885aa7, new_oid: dd7cee0df4fa8194f1cfd8c366910d7913885aa7, message: None }`
1. `RefUpdateEvent { timestamp: 1701606652.6007488, event_tx_id: EventTransactionId(22), ref_name: ReferenceName("HEAD"), old_oid: 0000000000000000000000000000000000000000, new_oid: 3e5d6fe3a882f2e53562104be6494f71d1cbd10b, message: None }`
1. `RefUpdateEvent { timestamp: 1701606652.728975, event_tx_id: EventTransactionId(22), ref_name: ReferenceName("HEAD"), old_oid: dd7cee0df4fa8194f1cfd8c366910d7913885aa7, new_oid: 3e5d6fe3a882f2e53562104be6494f71d1cbd10b, message: None }`
1. `RefUpdateEvent { timestamp: 1701606653.1773174, event_tx_id: EventTransactionId(22), ref_name: ReferenceName("HEAD"), old_oid: 3e5d6fe3a882f2e53562104be6494f71d1cbd10b, new_oid: d9b20d80e7e4988260eaa166753778fb475df55f, message: None }`
```
:
O da56717 258d xxxx xxxx xxxxx
|\
: o ec7bff6 254d (redacted-ref-0) xxxxxx xxxx
:
O 41f217a 75d (redacted-ref-1) xxxx xxx xxxx xx xxxxx
:
O b4de865 59d xxxxxx xxx xxxxx xxxxx
|\
: o 566ac90 59d (redacted-ref-2) xxxx xxxxxxxxx xxx xxxx
:
O c4a74e0 28d (redacted-ref-3) xxxx xxx xxxxxxxxx xxx xxxxxxx xxxx xxxx xxxxxxxxxx xxx xxxx xxx xxx xxxx
:
O 2ae7c32 28d (redacted-ref-4) xxxxx xxxxx xxxxxxx xxxxxxx xxxxxxx xx xx xxxx xxxx xxxxxxx xxxx
:
O 53fbd66 26d (redacted-ref-5) xxxxxx xxxxx xxxxxx xxx xxxx xxxxxxxxxx
:
O c88160a 26d xxxxx xxxx xxxxxxx xxx xxxx xxxxxxxxxxxxxxxxxx
|\
| o 6c1960f 26d xxxxx xxxxx xxxx xxxxx xxxx
| |
| o 7624998 25d xxxxx xxx xxxxxxxxxxx
| |
| o 8dfbbc6 25d xxxx xxxx xxxxx xxxxxxx xxx xxxxx
| |
| o 90fbfaa 25d xxx xxxxx xxxx
| |
| o 4c2f136 25d xxxx xxxx xxx xxx xxxxx xxxx
| |
| o 898bdc9 25d xxxx xxxxxx xx
| |
| o 02407ec 25d xxxxx xxxxxx xxxxxx
| |
| o fe949e3 25d xxxx xxxxx xx xxxxxx xx xxxxxxx xxxx
| |
| o 00139fc 25d xxxx xxxxxxxxx xxxx xx xxxxxx
| |
| o 7848514 25d xxxxxx xxxxxx
| |
| o 8be9311 25d xxxx xxxxx xxxx xxxxxx xxxxx
| |
| o 014b13a 25d (redacted-ref-6) xxxxxxxx
|
O d12c188 25d xxxxx xxxx xxxxx
|\
: o e108478 25d xxxxx xxxxxx xxxxxxxxxxxxxx
: |
: o f7af8f9 25d xxxx xxxx
: |
: o 2e2b044 25d xxxx xxxx xxxx xxxxxxx
: |
: o b6e474c 25d xxxxxx xxxx xxxxxx xxxxxx xxxx xxxx xx xxxx xxxx xxxxx xx xx
: |
: o 48dc8b5 25d xxxx xxxxxx xxxxxx xxxxxxxx xx xxxx
: |
: o a3f5b28 25d xxxx xxxxxxxx xxxxxx xx
: |
: o ca2fe47 25d xxxx xxx xxxxxx xxxxx xxxxx
: |
: o 6cbec51 25d xxxx xxxxxx xxxxx
: |
: o b1cad43 25d xxxx xxxxxx xxxxx xxxxx
: |
: o 56b56d9 25d xxxxx xxxx xxxx xx xxxxxx
: |
: o 0b850a8 25d xxxxx xxx xx xx xxx xxx xx
: |
: o f08112a 25d xxxx xxxx xxxxxx xxxx xxx xxxx xxxxxxxxx
: |
: o 61f71fb 24d (redacted-ref-7) xxxxxxxxxxxxxx xxxxxxxxxxxxxx xxxxxxx xxxxxxx xxx xxxxxxx xxxx
:
O 68491a7 23d (redacted-ref-8) xxxxxxxxx xxxx xxxxxxx
:
O 01bbc15 4d xxxx xxxxxx xxxxxxxx xxxxxxxx xx xxxxxxxxxxxx xxx xxx xxxxxxxx xx xx xxxxxxxxx
|\
: o 6e90a80 4d xxxxx xxxxxx xxxx xxx xxxxxxx xxxxxxxxx
: |
: o 9d482d6 4h xxxxxx xxxxxxxxxxx xx xx xxxxxx xxxx
: |
: o cb38414 26m xxxx xxxxxxx xxxxxxxxxxxxxx xxx xxx
: |\
: | o 2af5d7e 26m xxx xxxxxxx xxx xxxxxxx xxxxxxxxx xxxxxxx xxx xxxxxx xxxxxx xxxxxxx
: |
: o 9f1cde7 15m xxxx xxxxxxxxxx xxxxxxxxxxx xxxxx xx xxx xxxxxx xxxxxxxx
: |
: o 77a43fe 15m xxxx xxxxxxxx xx xxxxxx xxxxxxx xxxx xxxxxxxx xxxxxx xxxxxxxx
: |
: o 5140268 15m (redacted-ref-9) xxxxxxx xxx xxxxxx xxxxxxxx
:
@ d9b20d8 21m (main, redacted-ref-10) xxxxxx xxxxxxxxxxx xx xx xxxxxx xxxx
```
##### Event ID: 28, transaction ID: 21 (message: move)

1. `WorkingCopySnapshot { timestamp: 1701606577.3682947, event_tx_id: EventTransactionId(21), head_oid: d9b20d80e7e4988260eaa166753778fb475df55f, commit_oid: NonZeroOid(dd7cee0df4fa8194f1cfd8c366910d7913885aa7), ref_name: None }`
1. `RefUpdateEvent { timestamp: 1701606577.5194192, event_tx_id: EventTransactionId(21), ref_name: ReferenceName("HEAD"), old_oid: d9b20d80e7e4988260eaa166753778fb475df55f, new_oid: d9b20d80e7e4988260eaa166753778fb475df55f, message: None }`
```
:
O da56717 258d xxxx xxxx xxxxx
|\
: o ec7bff6 254d (redacted-ref-0) xxxxxx xxxx
:
O 41f217a 75d (redacted-ref-1) xxxx xxx xxxx xx xxxxx
:
O b4de865 59d xxxxxx xxx xxxxx xxxxx
|\
: o 566ac90 59d (redacted-ref-2) xxxx xxxxxxxxx xxx xxxx
:
O c4a74e0 28d (redacted-ref-3) xxxx xxx xxxxxxxxx xxx xxxxxxx xxxx xxxx xxxxxxxxxx xxx xxxx xxx xxx xxxx
:
O 2ae7c32 28d (redacted-ref-4) xxxxx xxxxx xxxxxxx xxxxxxx xxxxxxx xx xx xxxx xxxx xxxxxxx xxxx
:
O 53fbd66 26d (redacted-ref-5) xxxxxx xxxxx xxxxxx xxx xxxx xxxxxxxxxx
:
O c88160a 26d xxxxx xxxx xxxxxxx xxx xxxx xxxxxxxxxxxxxxxxxx
|\
| o 6c1960f 26d xxxxx xxxxx xxxx xxxxx xxxx
| |
| o 7624998 25d xxxxx xxx xxxxxxxxxxx
| |
| o 8dfbbc6 25d xxxx xxxx xxxxx xxxxxxx xxx xxxxx
| |
| o 90fbfaa 25d xxx xxxxx xxxx
| |
| o 4c2f136 25d xxxx xxxx xxx xxx xxxxx xxxx
| |
| o 898bdc9 25d xxxx xxxxxx xx
| |
| o 02407ec 25d xxxxx xxxxxx xxxxxx
| |
| o fe949e3 25d xxxx xxxxx xx xxxxxx xx xxxxxxx xxxx
| |
| o 00139fc 25d xxxx xxxxxxxxx xxxx xx xxxxxx
| |
| o 7848514 25d xxxxxx xxxxxx
| |
| o 8be9311 25d xxxx xxxxx xxxx xxxxxx xxxxx
| |
| o 014b13a 25d (redacted-ref-6) xxxxxxxx
|
O d12c188 25d xxxxx xxxx xxxxx
|\
: o e108478 25d xxxxx xxxxxx xxxxxxxxxxxxxx
: |
: o f7af8f9 25d xxxx xxxx
: |
: o 2e2b044 25d xxxx xxxx xxxx xxxxxxx
: |
: o b6e474c 25d xxxxxx xxxx xxxxxx xxxxxx xxxx xxxx xx xxxx xxxx xxxxx xx xx
: |
: o 48dc8b5 25d xxxx xxxxxx xxxxxx xxxxxxxx xx xxxx
: |
: o a3f5b28 25d xxxx xxxxxxxx xxxxxx xx
: |
: o ca2fe47 25d xxxx xxx xxxxxx xxxxx xxxxx
: |
: o 6cbec51 25d xxxx xxxxxx xxxxx
: |
: o b1cad43 25d xxxx xxxxxx xxxxx xxxxx
: |
: o 56b56d9 25d xxxxx xxxx xxxx xx xxxxxx
: |
: o 0b850a8 25d xxxxx xxx xx xx xxx xxx xx
: |
: o f08112a 25d xxxx xxxx xxxxxx xxxx xxx xxxx xxxxxxxxx
: |
: o 61f71fb 24d (redacted-ref-7) xxxxxxxxxxxxxx xxxxxxxxxxxxxx xxxxxxx xxxxxxx xxx xxxxxxx xxxx
:
O 68491a7 23d (redacted-ref-8) xxxxxxxxx xxxx xxxxxxx
:
O 01bbc15 4d xxxx xxxxxx xxxxxxxx xxxxxxxx xx xxxxxxxxxxxx xxx xxx xxxxxxxx xx xx xxxxxxxxx
|\
: o 6e90a80 4d xxxxx xxxxxx xxxx xxx xxxxxxx xxxxxxxxx
: |
: o 9d482d6 4h xxxxxx xxxxxxxxxxx xx xx xxxxxx xxxx
: |
: o cb38414 26m xxxx xxxxxxx xxxxxxxxxxxxxx xxx xxx
: |\
: | o 2af5d7e 26m xxx xxxxxxx xxx xxxxxxx xxxxxxxxx xxxxxxx xxx xxxxxx xxxxxx xxxxxxx
: |
: o 9f1cde7 15m xxxx xxxxxxxxxx xxxxxxxxxxx xxxxx xx xxx xxxxxx xxxxxxxx
: |
: o 77a43fe 15m xxxx xxxxxxxx xx xxxxxx xxxxxxx xxxx xxxxxxxx xxxxxx xxxxxxxx
: |
: o 5140268 15m (redacted-ref-9) xxxxxxx xxx xxxxxx xxxxxxxx
:
@ d9b20d8 21m (main, redacted-ref-10) xxxxxx xxxxxxxxxxx xx xx xxxxxx xxxx
```
##### Event ID: 27, transaction ID: 20 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1701606256.4774027, event_tx_id: EventTransactionId(20), ref_name: ReferenceName("refs/heads/redacted-ref-10"), old_oid: 0000000000000000000000000000000000000000, new_oid: d9b20d80e7e4988260eaa166753778fb475df55f, message: None }`
```
:
O da56717 258d xxxx xxxx xxxxx
|\
: o ec7bff6 254d (redacted-ref-0) xxxxxx xxxx
:
O 41f217a 75d (redacted-ref-1) xxxx xxx xxxx xx xxxxx
:
O b4de865 59d xxxxxx xxx xxxxx xxxxx
|\
: o 566ac90 59d (redacted-ref-2) xxxx xxxxxxxxx xxx xxxx
:
O c4a74e0 28d (redacted-ref-3) xxxx xxx xxxxxxxxx xxx xxxxxxx xxxx xxxx xxxxxxxxxx xxx xxxx xxx xxx xxxx
:
O 2ae7c32 28d (redacted-ref-4) xxxxx xxxxx xxxxxxx xxxxxxx xxxxxxx xx xx xxxx xxxx xxxxxxx xxxx
:
O 53fbd66 26d (redacted-ref-5) xxxxxx xxxxx xxxxxx xxx xxxx xxxxxxxxxx
:
O c88160a 26d xxxxx xxxx xxxxxxx xxx xxxx xxxxxxxxxxxxxxxxxx
|\
| o 6c1960f 26d xxxxx xxxxx xxxx xxxxx xxxx
| |
| o 7624998 25d xxxxx xxx xxxxxxxxxxx
| |
| o 8dfbbc6 25d xxxx xxxx xxxxx xxxxxxx xxx xxxxx
| |
| o 90fbfaa 25d xxx xxxxx xxxx
| |
| o 4c2f136 25d xxxx xxxx xxx xxx xxxxx xxxx
| |
| o 898bdc9 25d xxxx xxxxxx xx
| |
| o 02407ec 25d xxxxx xxxxxx xxxxxx
| |
| o fe949e3 25d xxxx xxxxx xx xxxxxx xx xxxxxxx xxxx
| |
| o 00139fc 25d xxxx xxxxxxxxx xxxx xx xxxxxx
| |
| o 7848514 25d xxxxxx xxxxxx
| |
| o 8be9311 25d xxxx xxxxx xxxx xxxxxx xxxxx
| |
| o 014b13a 25d (redacted-ref-6) xxxxxxxx
|
O d12c188 25d xxxxx xxxx xxxxx
|\
: o e108478 25d xxxxx xxxxxx xxxxxxxxxxxxxx
: |
: o f7af8f9 25d xxxx xxxx
: |
: o 2e2b044 25d xxxx xxxx xxxx xxxxxxx
: |
: o b6e474c 25d xxxxxx xxxx xxxxxx xxxxxx xxxx xxxx xx xxxx xxxx xxxxx xx xx
: |
: o 48dc8b5 25d xxxx xxxxxx xxxxxx xxxxxxxx xx xxxx
: |
: o a3f5b28 25d xxxx xxxxxxxx xxxxxx xx
: |
: o ca2fe47 25d xxxx xxx xxxxxx xxxxx xxxxx
: |
: o 6cbec51 25d xxxx xxxxxx xxxxx
: |
: o b1cad43 25d xxxx xxxxxx xxxxx xxxxx
: |
: o 56b56d9 25d xxxxx xxxx xxxx xx xxxxxx
: |
: o 0b850a8 25d xxxxx xxx xx xx xxx xxx xx
: |
: o f08112a 25d xxxx xxxx xxxxxx xxxx xxx xxxx xxxxxxxxx
: |
: o 61f71fb 24d (redacted-ref-7) xxxxxxxxxxxxxx xxxxxxxxxxxxxx xxxxxxx xxxxxxx xxx xxxxxxx xxxx
:
O 68491a7 23d (redacted-ref-8) xxxxxxxxx xxxx xxxxxxx
:
O 01bbc15 4d xxxx xxxxxx xxxxxxxx xxxxxxxx xx xxxxxxxxxxxx xxx xxx xxxxxxxx xx xx xxxxxxxxx
|\
: o 6e90a80 4d xxxxx xxxxxx xxxx xxx xxxxxxx xxxxxxxxx
: |
: o 9d482d6 4h xxxxxx xxxxxxxxxxx xx xx xxxxxx xxxx
: |
: o cb38414 26m xxxx xxxxxxx xxxxxxxxxxxxxx xxx xxx
: |\
: | o 2af5d7e 26m xxx xxxxxxx xxx xxxxxxx xxxxxxxxx xxxxxxx xxx xxxxxx xxxxxx xxxxxxx
: |
: o 9f1cde7 15m xxxx xxxxxxxxxx xxxxxxxxxxx xxxxx xx xxx xxxxxx xxxxxxxx
: |
: o 77a43fe 15m xxxx xxxxxxxx xx xxxxxx xxxxxxx xxxx xxxxxxxx xxxxxx xxxxxxxx
: |
: o 5140268 15m (redacted-ref-9) xxxxxxx xxx xxxxxx xxxxxxxx
:
@ d9b20d8 21m (main, redacted-ref-10) xxxxxx xxxxxxxxxxx xx xx xxxxxx xxxx
```
##### Event ID: 26, transaction ID: 19 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1701606242.7104185, event_tx_id: EventTransactionId(19), ref_name: ReferenceName("refs/remotes/redacted-ref-11"), old_oid: 0000000000000000000000000000000000000000, new_oid: d9b20d80e7e4988260eaa166753778fb475df55f, message: None }`
```
:
O da56717 258d xxxx xxxx xxxxx
|\
: o ec7bff6 254d (redacted-ref-0) xxxxxx xxxx
:
O 41f217a 75d (redacted-ref-1) xxxx xxx xxxx xx xxxxx
:
O b4de865 59d xxxxxx xxx xxxxx xxxxx
|\
: o 566ac90 59d (redacted-ref-2) xxxx xxxxxxxxx xxx xxxx
:
O c4a74e0 28d (redacted-ref-3) xxxx xxx xxxxxxxxx xxx xxxxxxx xxxx xxxx xxxxxxxxxx xxx xxxx xxx xxx xxxx
:
O 2ae7c32 28d (redacted-ref-4) xxxxx xxxxx xxxxxxx xxxxxxx xxxxxxx xx xx xxxx xxxx xxxxxxx xxxx
:
O 53fbd66 26d (redacted-ref-5) xxxxxx xxxxx xxxxxx xxx xxxx xxxxxxxxxx
:
O c88160a 26d xxxxx xxxx xxxxxxx xxx xxxx xxxxxxxxxxxxxxxxxx
|\
| o 6c1960f 26d xxxxx xxxxx xxxx xxxxx xxxx
| |
| o 7624998 25d xxxxx xxx xxxxxxxxxxx
| |
| o 8dfbbc6 25d xxxx xxxx xxxxx xxxxxxx xxx xxxxx
| |
| o 90fbfaa 25d xxx xxxxx xxxx
| |
| o 4c2f136 25d xxxx xxxx xxx xxx xxxxx xxxx
| |
| o 898bdc9 25d xxxx xxxxxx xx
| |
| o 02407ec 25d xxxxx xxxxxx xxxxxx
| |
| o fe949e3 25d xxxx xxxxx xx xxxxxx xx xxxxxxx xxxx
| |
| o 00139fc 25d xxxx xxxxxxxxx xxxx xx xxxxxx
| |
| o 7848514 25d xxxxxx xxxxxx
| |
| o 8be9311 25d xxxx xxxxx xxxx xxxxxx xxxxx
| |
| o 014b13a 25d (redacted-ref-6) xxxxxxxx
|
O d12c188 25d xxxxx xxxx xxxxx
|\
: o e108478 25d xxxxx xxxxxx xxxxxxxxxxxxxx
: |
: o f7af8f9 25d xxxx xxxx
: |
: o 2e2b044 25d xxxx xxxx xxxx xxxxxxx
: |
: o b6e474c 25d xxxxxx xxxx xxxxxx xxxxxx xxxx xxxx xx xxxx xxxx xxxxx xx xx
: |
: o 48dc8b5 25d xxxx xxxxxx xxxxxx xxxxxxxx xx xxxx
: |
: o a3f5b28 25d xxxx xxxxxxxx xxxxxx xx
: |
: o ca2fe47 25d xxxx xxx xxxxxx xxxxx xxxxx
: |
: o 6cbec51 25d xxxx xxxxxx xxxxx
: |
: o b1cad43 25d xxxx xxxxxx xxxxx xxxxx
: |
: o 56b56d9 25d xxxxx xxxx xxxx xx xxxxxx
: |
: o 0b850a8 25d xxxxx xxx xx xx xxx xxx xx
: |
: o f08112a 25d xxxx xxxx xxxxxx xxxx xxx xxxx xxxxxxxxx
: |
: o 61f71fb 24d (redacted-ref-7) xxxxxxxxxxxxxx xxxxxxxxxxxxxx xxxxxxx xxxxxxx xxx xxxxxxx xxxx
:
O 68491a7 23d (redacted-ref-8) xxxxxxxxx xxxx xxxxxxx
:
O 01bbc15 4d xxxx xxxxxx xxxxxxxx xxxxxxxx xx xxxxxxxxxxxx xxx xxx xxxxxxxx xx xx xxxxxxxxx
|\
: o 6e90a80 4d xxxxx xxxxxx xxxx xxx xxxxxxx xxxxxxxxx
: |
: o 9d482d6 4h xxxxxx xxxxxxxxxxx xx xx xxxxxx xxxx
: |
: o cb38414 26m xxxx xxxxxxx xxxxxxxxxxxxxx xxx xxx
: |\
: | o 2af5d7e 26m xxx xxxxxxx xxx xxxxxxx xxxxxxxxx xxxxxxx xxx xxxxxx xxxxxx xxxxxxx
: |
: o 9f1cde7 15m xxxx xxxxxxxxxx xxxxxxxxxxx xxxxx xx xxx xxxxxx xxxxxxxx
: |
: o 77a43fe 15m xxxx xxxxxxxx xx xxxxxx xxxxxxx xxxx xxxxxxxx xxxxxx xxxxxxxx
: |
: o 5140268 15m (redacted-ref-9) xxxxxxx xxx xxxxxx xxxxxxxx
:
@ d9b20d8 21m (main, redacted-ref-10) xxxxxx xxxxxxxxxxx xx xx xxxxxx xxxx

### Version of `git-branchless`

_No response_

### Version of `git`

_No response_

### LINKED ISSUE #1256: PATH's different names in Windows and Linux causing git-branchless hook execution to fail
I do a lot of game engine programming so i can't avoid using git under native windows. When using git-branchless, I also had similar problem as (#370 , #1144 ). Begin debugging...

In #370 

---

> Definitely seems like a git on Windows bug. Just sort of sucks because it makes git branchless sort of broken on Windows. I'm moved to exclusively using git in WSL/Ubuntu so it's no longer a problem for me on my home computer. I'm starting a new job next week which is going to be on Windows and I don't really know how I'll be interacting with source control and I don't know much about how the environment is set up. Depending on how that turns out, I may dig more into what it takes to make this work properly.

No,  This is not a Git for Windows problem, after I debugged it, I realized that it is due to the naming of the `Path` environment variable, in the following code, `git-branchless` reads the environment variable named `PATH`, but in windows, the variable name should be `Path`.

https://github.com/arxanas/git-branchless/blob/e7c3653c5e42f67a967d30ea57ded5a34cc6f9aa/git-branchless-lib/src/git/run.rs#L407-L422

I believe this is due to the fact that the windows shell is insensitive to the case of environment variable names (both pwsh and cmd), which many developers don't pay attention to on windows, you can read the environment variables correctly in the shell with `Path` `PATH` or even `PaTh`.

quick fix:

```rust
        let GitRunInfo {
            // We're calling a Git hook, but not Git itself.
            path_to_git: _,
            // We always want to call the hook in the Git working copy,
            // regardless of where the Git executable was invoked.
            working_directory: _,
            env,
        } = self;
        let path = {
            let mut path_components: Vec<PathBuf> =
                vec![std::fs::canonicalize(&hook_dir).wrap_err("Canonicalizing hook dir")?];
            if let Some(path) = env.get(OsStr::new("PATH")) {
                path_components.extend(std::env::split_paths(path));
            }
            #[cfg(target_os = "windows")]
            if let Some(path) = env.get(OsStr::new("Path")) {
                path_components.extend(std::env::split_paths(path));
            }
            std::env::join_paths(path_components).wrap_err("Joining path components")?
        };
```

---

yep, windows target's `std` crate also:

```rust
fn main() {
    println!("{:?}", std::env::var_os("Path")); // valid
    println!("{:?}", std::env::var_os("PATH")); // valid
    println!("{:?}", std::env::var_os("PaTh")); // valid
    // but 
    let x = std::env::vars_os().collect();
    // put "Path" inside x
}
```

_Originally posted by @c00t in https://github.com/arxanas/git-branchless/issues/370#issuecomment-1971239404_

### PR DESCRIPTION
**Pull request by c00t**
Closes #1256, closes #370, closes #1144

### CODE REVIEW

File: git-branchless-lib/src/git/run.rs [hunk 1]
```diff
@@ -418,6 +418,11 @@ impl GitRunInfo {
             if let Some(path) = env.get(OsStr::new("PATH")) {
                 path_components.extend(std::env::split_paths(path));
             }
+            // On windows, PATH's name defaults to "Path".
+            #[cfg(target_os = "windows")]
+            if let Some(path) = env.get(OsStr::new("Path")) {
```
Comment (arxanas) [inline git-branchless-lib/src/git/run.rs:423]: When possible, I like to use `if !cfg(target_os = "windows")` instead, as the compiler will typecheck the body of the `if`-expression then, but not a big deal here.

**Review by arxanas — APPROVED** [review]
Thanks!

**Comment by AaronLieberman** [comment]
This issue was the primary reason why I couldn't recommend git-branchless to others, glad you found and fixed it. Thanks much @c00t and @arxanas!
