### PR TITLE
Print query output in correct order

### LINKED ISSUE #554: `git-branchless query` prints commits in reverse order
### Description of the bug

According to [the documentation](https://github.com/arxanas/git-branchless/wiki/Command:-git-query#usage):

> The output is topologically-sorted, i.e. ancestor commits will appear before descendant commits in the list.

However, I seem to be seeing the opposite:

```sh
➜ git-branchless smartlog
⋮
◇ da757c2 1h (main, remote origin/main) Initial work for smarter `that` marks (#957)
┃
◯ 3104728 1h (foo-bar) A few actions support smarter `that` marks
┃
◯ 9841c5c 1h (pokey/some-smarter-that-marks) Update fixtures
┃
● 404fd54 4m (ᐅ pokey/testing) Kick CI

➜ git-branchless query "stack()"
404fd54 Kick CI
9841c5c Update fixtures
3104728 A few actions support smarter `that` marks
```

Note that I've abbreviated my smartlog here to only show the current stack

### Expected behavior

The commits appear in topological order

### Actual behavior

The commits appear in **reverse** topological order

### Version of `rustc`

rustc 1.62.1 (e092d0b6b 2022-07-16)

#### Software version

git-branchless 0.4.0

#### Operating system

macOS 12.4 (Darwin 21.5.0)

#### Command-line

```bash
/Users/pokey/.cargo/bin/git-branchless bug-report 
```

#### Environment variables

```bash
SHELL=/usr/local/bin/zsh
EDITOR=edit-in-vscode
```

#### Git version

```
> git version 
git version 2.33.1
```

#### Hooks

<details>
<summary>Show 6 hooks</summary>

##### Hook `post-commit`

```
#!/bin/sh

## START BRANCHLESS CONFIG

git branchless hook-post-commit "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-merge`

```
#!/bin/sh

## START BRANCHLESS CONFIG

git branchless hook-post-merge "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-rewrite`

```
#!/bin/sh

## START BRANCHLESS CONFIG

git branchless hook-post-rewrite "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-checkout`

```
#!/bin/sh

## START BRANCHLESS CONFIG

git branchless hook-post-checkout "$@"
## END BRANCHLESS CONFIG
```
##### Hook `pre-auto-gc`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-pre-auto-gc "$@"
## END BRANCHLESS CONFIG
```
##### Hook `reference-transaction`

```
#!/bin/sh
## START BRANCHLESS CONFIG

# Avoid canceling the reference transaction in the case that `branchless` fails
# for whatever reason.
git branchless hook-reference-transaction "$@" || (
echo 'branchless: Failed to process reference transaction!'
echo 'branchless: Some events (e.g. branch updates) may have been lost.'
echo 'branchless: This is a bug. Please report it.'
)
## END BRANCHLESS CONFIG
```

</details>

#### Events

<details>
<summary>Show 5 events</summary>

##### Event ID: 22703, transaction ID: 19705 (message: hook-post-checkout)

1. `RefUpdateEvent { timestamp: 1663774877.761121, event_tx_id: EventTransactionId(19705), ref_name: "HEAD", old_oid: 404fd540d4085267c242e4b55c650ee845404a10, new_oid: 404fd540d4085267c242e4b55c650ee845404a10, message: None }`
```
:
O 3d53c87 1y xxxxxxxx xxx xxxxxx xxxxxx
|\
: o 06047b9 1y xxxxxxx xxxx xxxxxx
: |
: o 8e63ce3 1y xxxxxx xxxxx
: |
: o 42308e5 1y (redacted-ref-0) xxxxxx xxxxxxxxxxx xxxxx xxx xxx
:
O cd8258f 1y xxx xxxxx xxxxx xxxxxx xx xxxxxx xxxxxx
|\
: o 5ff6852 1y (redacted-ref-1) xxxxxxxxxxxxxxxx xxxxxxx xxxxx
:
O f014bb6 329d xxxxxxx xxxxxx xxxxxx
|\
: o bfb6357 321d (redacted-ref-2) xxxxxxx xxxx
:
O a6bdb3a 317d xxxxxxx xx xxxxxxxxxxx xxxxxx
|\
: o 0683431 314d (redacted-ref-3) xxxxxxx xxxxxxx xxxx xxxxxx
:
O 39f91b7 142d xxxxx xxxxxxxxxx xxxxxxxxxx xxxxxxxx xxx x xxxxx xxxxxxxxx xxxxxx
|\
| o c8bf7b2 133d (redacted-ref-4) xxxxxxxx xxxxxxx
|\
: o 9672214 126d xxxxxxx xxxxxxxxxx xxxxxx
:
O f9b1bf0 106d xxxxxx xxxxxxxxxxxx xx xxxxxxxx xxxxxxxx xxxxxx xxxxxxxxxxxx xxxxxx
|\
: o 6ab32e2 105d xxxxxxx xxxx xxx xxxxxxxxxxx xxxxxxxx
:
O 10c355f 89d xxx xxxxxx xxxx xxxxxxxx xxxxxxx xx xxxx xxxx xxxxxx
|\
| o bf77b8c 89d xxxxxxx xxxxx xxxxxxxxxxx
| |
| o 9529dc3 89d (redacted-ref-5) xxxxx xxxxxxxxxx
|\
: o f931c9a 89d (redacted-ref-6) xxxxxxx xxxxxxxxxx xxxxxx
:
O 3419b74 76d xxx x xxxxxx xxxx xxxxxxxx xxxxxx
|\
: o 0f247a7 75d xxxxxx xxxxxxxxxxxxxxxx
: |
: o afba845 75d xxxxxxxxxx xxxxxxxx
: |
: o 81a6d9b 75d xxxxxxx xxxxxxxx xxxxx
: |
: o b3504a6 75d (redacted-ref-7) xxxx xx xxxxxx xxxx
:
O b639e42 64d xxx xxxxxxxxxxx xxxxxx
|\
: o 92a2cdc 64d xxxx xxxxx xxxx xxxxxxxxxx xxxx xxxxxx
: |
: o 3632e8d 64d xxx x xxxxxxx
: |
: o 5895e4c 14d (redacted-ref-8) xxxxxx xxxxx xx xx
:
O 560a7a1 4h xxxxx xxxxxxxxx xxxxxx xxxx xxxx xxxx xxxxxxxx xxxxxx
|\
| o 9916d85 4h (redacted-ref-9) xxxxxxx xxxxx xx xxxx xx xxxxxx
|\
| o 05e2a95 4h xxxx xx xxxxxxx xxxxxxxxxxx xxx xxxxx xxxxxxx
|\
| o 1b4ce7f 4h xxxxx xxxxxxxxx xxxxxxxxxxx xxxxxxx
| |
| o ee0b97f 4h xxxxx xxxxxx
| |
| o d30d01a 4h (redacted-ref-10) xxx
|\
| o 1f810a2 4h (redacted-ref-11) xxxxxx xxx xxxxxxxxxx
| |
| o ad7f85a 4h xxxxxxxxxxxxxxx xx xxxxxxxxxx
|\
| o 507cab1 4h xxx xxxxx xxxxxxxxxxx
| |
| o 59eb137 4h xxx xxxxx xxxxxxx
| |
| o bd53f94 4h (redacted-ref-12) xxx xxxxxxxx xxxxx
|\
| o 86362e9 4h (redacted-ref-13) xxxxxxx xxxxxx xx xxxxxxxxxxxxxxxx
|\
| o 8f8ed0a 4h xxxxxxx xxxxxxxxxxxxxxxxxx xxxxxx
| |
| o ea87d33 3h (redacted-ref-14) xxxxxxx xxxxxxxxxxxxx
|\
| o cf83144 4h xxxxxxxxxxxxxx xx xxxxxx xxx xxxxxx xxxxx
|\
| o d5f3eca 4h (redacted-ref-15) xxxx xxxxxxxx xxxxxxx
|\
| o f0ebe29 4h xxxxxx xxxxx
| |
| o ea5cc71 4h (redacted-ref-16) xxx xxxxxxxxxxxxxxxxxxxxxxx
|
O 6773798 3h xxxxxx xxxxxx xxxx xxxx xxxxxxxxxx xxxxx xxxxxx
|\
| o 6ee3910 2h (redacted-ref-17) xxxxx xxxx xxxxxxxxx
|
O 9195c6a 3h xxxxxxx xxxxxxx xxxxxxxx xxxxxx xxx xxxxxxxxx xxxxxx
|\
| o 0f325c7 2h xxxxxxx xxxxx xxxxxxxx xxxxxxx
| |
| o 185ee46 2h xxxxxxxxxxxxxxx xxxx xxxxx xxxx xxxxxxxxxxxxxx xxxxx
| |
| o bce398b 2h xxxxxxx xxxxxxxx xxxxxxx
| |
| o 397f28a 2h xxx
| |
| o 19b8f0a 2h (redacted-ref-18) xxxxxxx xx xxx xxxxxx xxxxx
|
O da757c2 1h (redacted-ref-19, remote origin/main) xxxxxxx xxxx xxx xxxxxxx xxxxxx xxxxx xxxxxx
|
o 3104728 1h (redacted-ref-20) x xxx xxxxxxx xxxxxxx xxxxxxx xxxxxx xxxxx
|
o 9841c5c 1h (redacted-ref-21) xxxxxx xxxxxxxx
|
@ 404fd54 8m (redacted-ref-22) xxxx xx
```
##### Event ID: 22702, transaction ID: 19704 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1663774877.718586, event_tx_id: EventTransactionId(19704), ref_name: "refs/heads/redacted-ref-22", old_oid: 0000000000000000000000000000000000000000, new_oid: 404fd540d4085267c242e4b55c650ee845404a10, message: None }`
```
:
O 3d53c87 1y xxxxxxxx xxx xxxxxx xxxxxx
|\
: o 06047b9 1y xxxxxxx xxxx xxxxxx
: |
: o 8e63ce3 1y xxxxxx xxxxx
: |
: o 42308e5 1y (redacted-ref-0) xxxxxx xxxxxxxxxxx xxxxx xxx xxx
:
O cd8258f 1y xxx xxxxx xxxxx xxxxxx xx xxxxxx xxxxxx
|\
: o 5ff6852 1y (redacted-ref-1) xxxxxxxxxxxxxxxx xxxxxxx xxxxx
:
O f014bb6 329d xxxxxxx xxxxxx xxxxxx
|\
: o bfb6357 321d (redacted-ref-2) xxxxxxx xxxx
:
O a6bdb3a 317d xxxxxxx xx xxxxxxxxxxx xxxxxx
|\
: o 0683431 314d (redacted-ref-3) xxxxxxx xxxxxxx xxxx xxxxxx
:
O 39f91b7 142d xxxxx xxxxxxxxxx xxxxxxxxxx xxxxxxxx xxx x xxxxx xxxxxxxxx xxxxxx
|\
| o c8bf7b2 133d (redacted-ref-4) xxxxxxxx xxxxxxx
|\
: o 9672214 126d xxxxxxx xxxxxxxxxx xxxxxx
:
O f9b1bf0 106d xxxxxx xxxxxxxxxxxx xx xxxxxxxx xxxxxxxx xxxxxx xxxxxxxxxxxx xxxxxx
|\
: o 6ab32e2 105d xxxxxxx xxxx xxx xxxxxxxxxxx xxxxxxxx
:
O 10c355f 89d xxx xxxxxx xxxx xxxxxxxx xxxxxxx xx xxxx xxxx xxxxxx
|\
| o bf77b8c 89d xxxxxxx xxxxx xxxxxxxxxxx
| |
| o 9529dc3 89d (redacted-ref-5) xxxxx xxxxxxxxxx
|\
: o f931c9a 89d (redacted-ref-6) xxxxxxx xxxxxxxxxx xxxxxx
:
O 3419b74 76d xxx x xxxxxx xxxx xxxxxxxx xxxxxx
|\
: o 0f247a7 75d xxxxxx xxxxxxxxxxxxxxxx
: |
: o afba845 75d xxxxxxxxxx xxxxxxxx
: |
: o 81a6d9b 75d xxxxxxx xxxxxxxx xxxxx
: |
: o b3504a6 75d (redacted-ref-7) xxxx xx xxxxxx xxxx
:
O b639e42 64d xxx xxxxxxxxxxx xxxxxx
|\
: o 92a2cdc 64d xxxx xxxxx xxxx xxxxxxxxxx xxxx xxxxxx
: |
: o 3632e8d 64d xxx x xxxxxxx
: |
: o 5895e4c 14d (redacted-ref-8) xxxxxx xxxxx xx xx
:
O 560a7a1 4h xxxxx xxxxxxxxx xxxxxx xxxx xxxx xxxx xxxxxxxx xxxxxx
|\
| o 9916d85 4h (redacted-ref-9) xxxxxxx xxxxx xx xxxx xx xxxxxx
|\
| o 05e2a95 4h xxxx xx xxxxxxx xxxxxxxxxxx xxx xxxxx xxxxxxx
|\
| o 1b4ce7f 4h xxxxx xxxxxxxxx xxxxxxxxxxx xxxxxxx
| |
| o ee0b97f 4h xxxxx xxxxxx
| |
| o d30d01a 4h (redacted-ref-10) xxx
|\
| o 1f810a2 4h (redacted-ref-11) xxxxxx xxx xxxxxxxxxx
| |
| o ad7f85a 4h xxxxxxxxxxxxxxx xx xxxxxxxxxx
|\
| o 507cab1 4h xxx xxxxx xxxxxxxxxxx
| |
| o 59eb137 4h xxx xxxxx xxxxxxx
| |
| o bd53f94 4h (redacted-ref-12) xxx xxxxxxxx xxxxx
|\
| o 86362e9 4h (redacted-ref-13) xxxxxxx xxxxxx xx xxxxxxxxxxxxxxxx
|\
| o 8f8ed0a 4h xxxxxxx xxxxxxxxxxxxxxxxxx xxxxxx
| |
| o ea87d33 3h (redacted-ref-14) xxxxxxx xxxxxxxxxxxxx
|\
| o cf83144 4h xxxxxxxxxxxxxx xx xxxxxx xxx xxxxxx xxxxx
|\
| o d5f3eca 4h (redacted-ref-15) xxxx xxxxxxxx xxxxxxx
|\
| o f0ebe29 4h xxxxxx xxxxx
| |
| o ea5cc71 4h (redacted-ref-16) xxx xxxxxxxxxxxxxxxxxxxxxxx
|
O 6773798 3h xxxxxx xxxxxx xxxx xxxx xxxxxxxxxx xxxxx xxxxxx
|\
| o 6ee3910 2h (redacted-ref-17) xxxxx xxxx xxxxxxxxx
|
O 9195c6a 3h xxxxxxx xxxxxxx xxxxxxxx xxxxxx xxx xxxxxxxxx xxxxxx
|\
| o 0f325c7 2h xxxxxxx xxxxx xxxxxxxx xxxxxxx
| |
| o 185ee46 2h xxxxxxxxxxxxxxx xxxx xxxxx xxxx xxxxxxxxxxxxxx xxxxx
| |
| o bce398b 2h xxxxxxx xxxxxxxx xxxxxxx
| |
| o 397f28a 2h xxx
| |
| o 19b8f0a 2h (redacted-ref-18) xxxxxxx xx xxx xxxxxx xxxxx
|
O da757c2 1h (redacted-ref-19, remote origin/main) xxxxxxx xxxx xxx xxxxxxx xxxxxx xxxxx xxxxxx
|
o 3104728 1h (redacted-ref-20) x xxx xxxxxxx xxxxxxx xxxxxxx xxxxxx xxxxx
|
o 9841c5c 1h (redacted-ref-21) xxxxxx xxxxxxxx
|
@ 404fd54 8m (redacted-ref-22) xxxx xx
```
##### Event ID: 22701, transaction ID: 19703 (message: post-commit)

1. `CommitEvent { timestamp: 1663774836.0, event_tx_id: EventTransactionId(19703), commit_oid: NonZeroOid(404fd540d4085267c242e4b55c650ee845404a10) }`
```
:
O 3d53c87 1y xxxxxxxx xxx xxxxxx xxxxxx
|\
: o 06047b9 1y xxxxxxx xxxx xxxxxx
: |
: o 8e63ce3 1y xxxxxx xxxxx
: |
: o 42308e5 1y (redacted-ref-0) xxxxxx xxxxxxxxxxx xxxxx xxx xxx
:
O cd8258f 1y xxx xxxxx xxxxx xxxxxx xx xxxxxx xxxxxx
|\
: o 5ff6852 1y (redacted-ref-1) xxxxxxxxxxxxxxxx xxxxxxx xxxxx
:
O f014bb6 329d xxxxxxx xxxxxx xxxxxx
|\
: o bfb6357 321d (redacted-ref-2) xxxxxxx xxxx
:
O a6bdb3a 317d xxxxxxx xx xxxxxxxxxxx xxxxxx
|\
: o 0683431 314d (redacted-ref-3) xxxxxxx xxxxxxx xxxx xxxxxx
:
O 39f91b7 142d xxxxx xxxxxxxxxx xxxxxxxxxx xxxxxxxx xxx x xxxxx xxxxxxxxx xxxxxx
|\
| o c8bf7b2 133d (redacted-ref-4) xxxxxxxx xxxxxxx
|\
: o 9672214 126d xxxxxxx xxxxxxxxxx xxxxxx
:
O f9b1bf0 106d xxxxxx xxxxxxxxxxxx xx xxxxxxxx xxxxxxxx xxxxxx xxxxxxxxxxxx xxxxxx
|\
: o 6ab32e2 105d xxxxxxx xxxx xxx xxxxxxxxxxx xxxxxxxx
:
O 10c355f 89d xxx xxxxxx xxxx xxxxxxxx xxxxxxx xx xxxx xxxx xxxxxx
|\
| o bf77b8c 89d xxxxxxx xxxxx xxxxxxxxxxx
| |
| o 9529dc3 89d (redacted-ref-5) xxxxx xxxxxxxxxx
|\
: o f931c9a 89d (redacted-ref-6) xxxxxxx xxxxxxxxxx xxxxxx
:
O 3419b74 76d xxx x xxxxxx xxxx xxxxxxxx xxxxxx
|\
: o 0f247a7 75d xxxxxx xxxxxxxxxxxxxxxx
: |
: o afba845 75d xxxxxxxxxx xxxxxxxx
: |
: o 81a6d9b 75d xxxxxxx xxxxxxxx xxxxx
: |
: o b3504a6 75d (redacted-ref-7) xxxx xx xxxxxx xxxx
:
O b639e42 64d xxx xxxxxxxxxxx xxxxxx
|\
: o 92a2cdc 64d xxxx xxxxx xxxx xxxxxxxxxx xxxx xxxxxx
: |
: o 3632e8d 64d xxx x xxxxxxx
: |
: o 5895e4c 14d (redacted-ref-8) xxxxxx xxxxx xx xx
:
O 560a7a1 4h xxxxx xxxxxxxxx xxxxxx xxxx xxxx xxxx xxxxxxxx xxxxxx
|\
| o 9916d85 4h (redacted-ref-9) xxxxxxx xxxxx xx xxxx xx xxxxxx
|\
| o 05e2a95 4h xxxx xx xxxxxxx xxxxxxxxxxx xxx xxxxx xxxxxxx
|\
| o 1b4ce7f 4h xxxxx xxxxxxxxx xxxxxxxxxxx xxxxxxx
| |
| o ee0b97f 4h xxxxx xxxxxx
| |
| o d30d01a 4h (redacted-ref-10) xxx
|\
| o 1f810a2 4h (redacted-ref-11) xxxxxx xxx xxxxxxxxxx
| |
| o ad7f85a 4h xxxxxxxxxxxxxxx xx xxxxxxxxxx
|\
| o 507cab1 4h xxx xxxxx xxxxxxxxxxx
| |
| o 59eb137 4h xxx xxxxx xxxxxxx
| |
| o bd53f94 4h (redacted-ref-12) xxx xxxxxxxx xxxxx
|\
| o 86362e9 4h (redacted-ref-13) xxxxxxx xxxxxx xx xxxxxxxxxxxxxxxx
|\
| o 8f8ed0a 4h xxxxxxx xxxxxxxxxxxxxxxxxx xxxxxx
| |
| o ea87d33 3h (redacted-ref-14) xxxxxxx xxxxxxxxxxxxx
|\
| o cf83144 4h xxxxxxxxxxxxxx xx xxxxxx xxx xxxxxx xxxxx
|\
| o d5f3eca 4h (redacted-ref-15) xxxx xxxxxxxx xxxxxxx
|\
| o f0ebe29 4h xxxxxx xxxxx
| |
| o ea5cc71 4h (redacted-ref-16) xxx xxxxxxxxxxxxxxxxxxxxxxx
|
O 6773798 3h xxxxxx xxxxxx xxxx xxxx xxxxxxxxxx xxxxx xxxxxx
|\
| o 6ee3910 2h (redacted-ref-17) xxxxx xxxx xxxxxxxxx
|
O 9195c6a 3h xxxxxxx xxxxxxx xxxxxxxx xxxxxx xxx xxxxxxxxx xxxxxx
|\
| o 0f325c7 2h xxxxxxx xxxxx xxxxxxxx xxxxxxx
| |
| o 185ee46 2h xxxxxxxxxxxxxxx xxxx xxxxx xxxx xxxxxxxxxxxxxx xxxxx
| |
| o bce398b 2h xxxxxxx xxxxxxxx xxxxxxx
| |
| o 397f28a 2h xxx
| |
| o 19b8f0a 2h (redacted-ref-18) xxxxxxx xx xxx xxxxxx xxxxx
|
O da757c2 1h (redacted-ref-19, remote origin/main) xxxxxxx xxxx xxx xxxxxxx xxxxxx xxxxx xxxxxx
|
o 3104728 1h (redacted-ref-20) x xxx xxxxxxx xxxxxxx xxxxxxx xxxxxx xxxxx
|
o 9841c5c 1h (redacted-ref-21) xxxxxx xxxxxxxx
|
@ 404fd54 8m (redacted-ref-22) xxxx xx
```
##### Event ID: 22700, transaction ID: 19702 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1663774836.846817, event_tx_id: EventTransactionId(19702), ref_name: "HEAD", old_oid: 9841c5ce5de461959a5134ee099bc9632baaac1e, new_oid: 404fd540d4085267c242e4b55c650ee845404a10, message: None }`
```
:
O 3d53c87 1y xxxxxxxx xxx xxxxxx xxxxxx
|\
: o 06047b9 1y xxxxxxx xxxx xxxxxx
: |
: o 8e63ce3 1y xxxxxx xxxxx
: |
: o 42308e5 1y (redacted-ref-0) xxxxxx xxxxxxxxxxx xxxxx xxx xxx
:
O cd8258f 1y xxx xxxxx xxxxx xxxxxx xx xxxxxx xxxxxx
|\
: o 5ff6852 1y (redacted-ref-1) xxxxxxxxxxxxxxxx xxxxxxx xxxxx
:
O f014bb6 329d xxxxxxx xxxxxx xxxxxx
|\
: o bfb6357 321d (redacted-ref-2) xxxxxxx xxxx
:
O a6bdb3a 317d xxxxxxx xx xxxxxxxxxxx xxxxxx
|\
: o 0683431 314d (redacted-ref-3) xxxxxxx xxxxxxx xxxx xxxxxx
:
O 39f91b7 142d xxxxx xxxxxxxxxx xxxxxxxxxx xxxxxxxx xxx x xxxxx xxxxxxxxx xxxxxx
|\
| o c8bf7b2 133d (redacted-ref-4) xxxxxxxx xxxxxxx
|\
: o 9672214 126d xxxxxxx xxxxxxxxxx xxxxxx
:
O f9b1bf0 106d xxxxxx xxxxxxxxxxxx xx xxxxxxxx xxxxxxxx xxxxxx xxxxxxxxxxxx xxxxxx
|\
: o 6ab32e2 105d xxxxxxx xxxx xxx xxxxxxxxxxx xxxxxxxx
:
O 10c355f 89d xxx xxxxxx xxxx xxxxxxxx xxxxxxx xx xxxx xxxx xxxxxx
|\
| o bf77b8c 89d xxxxxxx xxxxx xxxxxxxxxxx
| |
| o 9529dc3 89d (redacted-ref-5) xxxxx xxxxxxxxxx
|\
: o f931c9a 89d (redacted-ref-6) xxxxxxx xxxxxxxxxx xxxxxx
:
O 3419b74 76d xxx x xxxxxx xxxx xxxxxxxx xxxxxx
|\
: o 0f247a7 75d xxxxxx xxxxxxxxxxxxxxxx
: |
: o afba845 75d xxxxxxxxxx xxxxxxxx
: |
: o 81a6d9b 75d xxxxxxx xxxxxxxx xxxxx
: |
: o b3504a6 75d (redacted-ref-7) xxxx xx xxxxxx xxxx
:
O b639e42 64d xxx xxxxxxxxxxx xxxxxx
|\
: o 92a2cdc 64d xxxx xxxxx xxxx xxxxxxxxxx xxxx xxxxxx
: |
: o 3632e8d 64d xxx x xxxxxxx
: |
: o 5895e4c 14d (redacted-ref-8) xxxxxx xxxxx xx xx
:
O 560a7a1 4h xxxxx xxxxxxxxx xxxxxx xxxx xxxx xxxx xxxxxxxx xxxxxx
|\
| o 9916d85 4h (redacted-ref-9) xxxxxxx xxxxx xx xxxx xx xxxxxx
|\
| o 05e2a95 4h xxxx xx xxxxxxx xxxxxxxxxxx xxx xxxxx xxxxxxx
|\
| o 1b4ce7f 4h xxxxx xxxxxxxxx xxxxxxxxxxx xxxxxxx
| |
| o ee0b97f 4h xxxxx xxxxxx
| |
| o d30d01a 4h (redacted-ref-10) xxx
|\
| o 1f810a2 4h (redacted-ref-11) xxxxxx xxx xxxxxxxxxx
| |
| o ad7f85a 4h xxxxxxxxxxxxxxx xx xxxxxxxxxx
|\
| o 507cab1 4h xxx xxxxx xxxxxxxxxxx
| |
| o 59eb137 4h xxx xxxxx xxxxxxx
| |
| o bd53f94 4h (redacted-ref-12) xxx xxxxxxxx xxxxx
|\
| o 86362e9 4h (redacted-ref-13) xxxxxxx xxxxxx xx xxxxxxxxxxxxxxxx
|\
| o 8f8ed0a 4h xxxxxxx xxxxxxxxxxxxxxxxxx xxxxxx
| |
| o ea87d33 3h (redacted-ref-14) xxxxxxx xxxxxxxxxxxxx
|\
| o cf83144 4h xxxxxxxxxxxxxx xx xxxxxx xxx xxxxxx xxxxx
|\
| o d5f3eca 4h (redacted-ref-15) xxxx xxxxxxxx xxxxxxx
|\
| o f0ebe29 4h xxxxxx xxxxx
| |
| o ea5cc71 4h (redacted-ref-16) xxx xxxxxxxxxxxxxxxxxxxxxxx
|
O 6773798 3h xxxxxx xxxxxx xxxx xxxx xxxxxxxxxx xxxxx xxxxxx
|\
| o 6ee3910 2h (redacted-ref-17) xxxxx xxxx xxxxxxxxx
|
O 9195c6a 3h xxxxxxx xxxxxxx xxxxxxxx xxxxxx xxx xxxxxxxxx xxxxxx
|\
| o 0f325c7 2h xxxxxxx xxxxx xxxxxxxx xxxxxxx
| |
| o 185ee46 2h xxxxxxxxxxxxxxx xxxx xxxxx xxxx xxxxxxxxxxxxxx xxxxx
| |
| o bce398b 2h xxxxxxx xxxxxxxx xxxxxxx
| |
| o 397f28a 2h xxx
| |
| o 19b8f0a 2h (redacted-ref-18) xxxxxxx xx xxx xxxxxx xxxxx
|
O da757c2 1h (redacted-ref-19, remote origin/main) xxxxxxx xxxx xxx xxxxxxx xxxxxx xxxxx xxxxxx
|
o 3104728 1h (redacted-ref-20) x xxx xxxxxxx xxxxxxx xxxxxxx xxxxxx xxxxx
|
o 9841c5c 1h (redacted-ref-21) xxxxxx xxxxxxxx
|
@ 404fd54 8m (redacted-ref-22) xxxx xx
```
##### Event ID: 22699, transaction ID: 19701 (message: hook-post-checkout)

1. `RefUpdateEvent { timestamp: 1663774832.338984, event_tx_id: EventTransactionId(19701), ref_name: "HEAD", old_oid: 9841c5ce5de461959a5134ee099bc9632baaac1e, new_oid: 9841c5ce5de461959a5134ee099bc9632baaac1e, message: None }`
```
:
O 3d53c87 1y xxxxxxxx xxx xxxxxx xxxxxx
|\
: o 06047b9 1y xxxxxxx xxxx xxxxxx
: |
: o 8e63ce3 1y xxxxxx xxxxx
: |
: o 42308e5 1y (redacted-ref-0) xxxxxx xxxxxxxxxxx xxxxx xxx xxx
:
O cd8258f 1y xxx xxxxx xxxxx xxxxxx xx xxxxxx xxxxxx
|\
: o 5ff6852 1y (redacted-ref-1) xxxxxxxxxxxxxxxx xxxxxxx xxxxx
:
O f014bb6 329d xxxxxxx xxxxxx xxxxxx
|\
: o bfb6357 321d (redacted-ref-2) xxxxxxx xxxx
:
O a6bdb3a 317d xxxxxxx xx xxxxxxxxxxx xxxxxx
|\
: o 0683431 314d (redacted-ref-3) xxxxxxx xxxxxxx xxxx xxxxxx
:
O 39f91b7 142d xxxxx xxxxxxxxxx xxxxxxxxxx xxxxxxxx xxx x xxxxx xxxxxxxxx xxxxxx
|\
| o c8bf7b2 133d (redacted-ref-4) xxxxxxxx xxxxxxx
|\
: o 9672214 126d xxxxxxx xxxxxxxxxx xxxxxx
:
O f9b1bf0 106d xxxxxx xxxxxxxxxxxx xx xxxxxxxx xxxxxxxx xxxxxx xxxxxxxxxxxx xxxxxx
|\
: o 6ab32e2 105d xxxxxxx xxxx xxx xxxxxxxxxxx xxxxxxxx
:
O 10c355f 89d xxx xxxxxx xxxx xxxxxxxx xxxxxxx xx xxxx xxxx xxxxxx
|\
| o bf77b8c 89d xxxxxxx xxxxx xxxxxxxxxxx
| |
| o 9529dc3 89d (redacted-ref-5) xxxxx xxxxxxxxxx
|\
: o f931c9a 89d (redacted-ref-6) xxxxxxx xxxxxxxxxx xxxxxx
:
O 3419b74 76d xxx x xxxxxx xxxx xxxxxxxx xxxxxx
|\
: o 0f247a7 75d xxxxxx xxxxxxxxxxxxxxxx
: |
: o afba845 75d xxxxxxxxxx xxxxxxxx
: |
: o 81a6d9b 75d xxxxxxx xxxxxxxx xxxxx
: |
: o b3504a6 75d (redacted-ref-7) xxxx xx xxxxxx xxxx
:
O b639e42 64d xxx xxxxxxxxxxx xxxxxx
|\
: o 92a2cdc 64d xxxx xxxxx xxxx xxxxxxxxxx xxxx xxxxxx
: |
: o 3632e8d 64d xxx x xxxxxxx
: |
: o 5895e4c 14d (redacted-ref-8) xxxxxx xxxxx xx xx
:
O 560a7a1 4h xxxxx xxxxxxxxx xxxxxx xxxx xxxx xxxx xxxxxxxx xxxxxx
|\
| o 9916d85 4h (redacted-ref-9) xxxxxxx xxxxx xx xxxx xx xxxxxx
|\
| o 05e2a95 4h xxxx xx xxxxxxx xxxxxxxxxxx xxx xxxxx xxxxxxx
|\
| o 1b4ce7f 4h xxxxx xxxxxxxxx xxxxxxxxxxx xxxxxxx
| |
| o ee0b97f 4h xxxxx xxxxxx
| |
| o d30d01a 4h (redacted-ref-10) xxx
|\
| o 1f810a2 4h (redacted-ref-11) xxxxxx xxx xxxxxxxxxx
| |
| o ad7f85a 4h xxxxxxxxxxxxxxx xx xxxxxxxxxx
|\
| o 507cab1 4h xxx xxxxx xxxxxxxxxxx
| |
| o 59eb137 4h xxx xxxxx xxxxxxx
| |
| o bd53f94 4h (redacted-ref-12) xxx xxxxxxxx xxxxx
|\
| o 86362e9 4h (redacted-ref-13) xxxxxxx xxxxxx xx xxxxxxxxxxxxxxxx
|\
| o 8f8ed0a 4h xxxxxxx xxxxxxxxxxxxxxxxxx xxxxxx
| |
| o ea87d33 3h (redacted-ref-14) xxxxxxx xxxxxxxxxxxxx
|\
| o cf83144 4h xxxxxxxxxxxxxx xx xxxxxx xxx xxxxxx xxxxx
|\
| o d5f3eca 4h (redacted-ref-15) xxxx xxxxxxxx xxxxxxx
|\
| o f0ebe29 4h xxxxxx xxxxx
| |
| o ea5cc71 4h (redacted-ref-16) xxx xxxxxxxxxxxxxxxxxxxxxxx
|
O 6773798 3h xxxxxx xxxxxx xxxx xxxx xxxxxxxxxx xxxxx xxxxxx
|\
| o 6ee3910 2h (redacted-ref-17) xxxxx xxxx xxxxxxxxx
|
O 9195c6a 3h xxxxxxx xxxxxxx xxxxxxxx xxxxxx xxx xxxxxxxxx xxxxxx
|\
| o 0f325c7 2h xxxxxxx xxxxx xxxxxxxx xxxxxxx
| |
| o 185ee46 2h xxxxxxxxxxxxxxx xxxx xxxxx xxxx xxxxxxxxxxxxxx xxxxx
| |
| o bce398b 2h xxxxxxx xxxxxxxx xxxxxxx
| |
| o 397f28a 2h xxx
| |
| o 19b8f0a 2h (redacted-ref-18) xxxxxxx xx xxx xxxxxx xxxxx
|
O da757c2 1h (redacted-ref-19, remote origin/main) xxxxxxx xxxx xxx xxxxxxx xxxxxx xxxxx xxxxxx
|
o 3104728 1h (redacted-ref-20) x xxx xxxxxxx xxxxxxx xxxxxxx xxxxxx xxxxx
|
o 9841c5c 1h (redacted-ref-21) xxxxxx xxxxxxxx
|
@ 404fd54 8m (redacted-ref-22) xxxx xx
```

</details>

### Version of `git-branchless`

git-branchless 0.4.0

### Version of `git`

git version 2.33.1

### PR DESCRIPTION
**Pull request by pokey**
Fixes #554

### CODE REVIEW

File: git-branchless/src/commands/query.rs [hunk 1]
```diff
@@ -49,12 +49,13 @@ pub fn query(
             let (effects, _progress) = effects.start_operation(OperationType::SortCommits);
             let _effects = effects;
 
-            let commit_set = dag.query().sort(&commit_set)?;
             let commit_set = commit_set.intersection(&dag.branch_commits);
-            commit_set_to_vec_unsorted(&commit_set)?
+            let commit_set = dag.query().sort(&commit_set)?;
```
Comment (pokey) [inline git-branchless/src/commands/query.rs:53]: Seemed better to sort after intersecting, just in case intersection doesn't preserve order

**Review by arxanas — APPROVED** [review]
💯
