### PR TITLE
Attempt to fix flaky undo tests (closes #23)

### LINKED ISSUE #23: flake: test_undo_hide
Just noticed this.  Happened on a run of run-tests against git `2.29.2`.

https://github.com/waych/git-branchless/runs/2898734801 

May be related to the `commit -a` observation?

```
---- command::test_undo::test_undo_hide stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: undo_hide-5
Source: tests/command/test_undo.rs:282
-old snapshot
+new results
────────────────────────────────────────────────────────────────────────────────
stdout
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ O f777ecc9 (master) create initial.txt
    1     1 │ |\
    2       │-| o 62fc20d2 (test1) create test1.txt
          2 │+| @ 62fc20d2 (test1) create test1.txt
    3     3 │ |
    4       │-@ fe65c1fe create test2.txt
          4 │+o fe65c1fe create test2.txt
────────────┴───────────────────────────────────────────────────────────────────
thread 'command::test_undo::test_undo_hide' panicked at 'snapshot assertion for 'undo_hide-5' failed in line 282', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.7.1/src/runtime.rs:1036:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    command::test_undo::test_undo_hide
```

### PR DESCRIPTION
**Pull request by arxanas**
- refactor(util): rename `GitExecutable` to `GitRunInfo`
- refactor(util): store more environment information in `GitRunInfo`

### CODE REVIEW

File: src/util.rs [hunk 1]
```diff
@@ -275,17 +287,34 @@ pub fn run_hook(
...
+            working_directory: _,
+            env,
+        } = git_run_info;
         let mut child = Command::new(get_sh().context("shell needed to run hook")?)
             .arg("-c")
-            // This is always passed as a current dir unix path, as `sh` is processing it as an
-            // argument, even on Windows.
-            .arg(format!("./{} \"$@\"", hook_name))
+            .arg(format!(
+                "{} \"$@\"",
```
Comment (waych) [inline src/util.rs:303]: FYI this argument needed the `./` prefix on Windows it wouldn't look in current directory otherwise.  I think this is due to gitbash's weird argument path translation, but am not sure.

Comment (arxanas) [reply src/util.rs:303]: Technically, there's no stipulation that the hook directory has to be somewhere under the current repository, such as if `git.core.hooksPath` is set to something else, so I think it's wrong to use `./` in this case.

Comment (waych) [reply src/util.rs:303]: Hmm actually I don't understand why the `./` isn't needed in Linux also: it isn't like we are expecting `.` to be in $PATH(?)

Comment (waych) [reply src/util.rs:307]: Ah I see you removed the `.current_dir(hook_path)`  which made the `./` correct 😄

Comment (waych) [reply src/util.rs:316]: I see what is happening.  See this line in the `bash` manpage:

```
If  the name is neither a shell function nor a builtin, and contains no slashes, bash searches each element of the PATH for a directory containing an executable file by that name.
```

and later

```If the search is successful, or if the command name contains one or more slashes, the shell executes the named program in a separate execution  environment.
```

Because `std::fs::canonicalize(&hook_path)` most certainly does contain `/`, the shell is interpreting it as a path to binary, whereas on Windows, lacking a '/' it is falling back to searching via PATH.  This explains why it worked for me when I added the `./` prefix unconditionally.


`std::fs::canonicalize(&hook_path)`

Comment (waych) [reply src/util.rs:316]: Thinking about ways this could be fixed without resorting to path mangling, it feels like the simplest way to resolve is to just add the canonicalized hook_path to the start of PATH and invoke the hook by name directly.

**Comment by arxanas** [comment]
Thanks for the help!
